# Generated by Django 3.0.2 on 2020-07-30 18:26

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labeldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='tabletask',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=1000)),
                ('inputfilelocation', models.CharField(max_length=100000)),
                ('outputfilelocatin', models.CharField(max_length=100000)),
                ('processedfilelocation', models.CharField(max_length=100000)),
                ('excelfilename', models.CharField(max_length=100000)),
                ('totalnumberoffiles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='task_creation',
            fields=[
                ('task_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_desc', models.CharField(max_length=100)),
                ('template_id', models.CharField(max_length=100)),
                ('input_file_name', models.CharField(max_length=1000)),
                ('output_file_name', models.CharField(max_length=1000)),
                ('file_name_pattern', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('myfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx'])])),
            ],
        ),
        migrations.CreateModel(
            name='viewdatafilepath',
            fields=[
                ('dataid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=1000)),
                ('inputfilelocation', models.CharField(max_length=10000)),
                ('filename', models.CharField(max_length=10000)),
                ('EngineData', models.TextField()),
                ('dataextracted', models.IntegerField()),
                ('dataaccuracy', models.IntegerField()),
                ('noisepercentage', models.IntegerField()),
                ('totalpages', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=1000)),
                ('EngineData1', jsonfield.fields.JSONField(default='')),
            ],
        ),
    ]
